---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-nfs-01
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.0
    - timeo=60
    - retrans=10
  capacity:
    storage: 10Gi
  nfs:
    server: 10.0.0.20
    path: "/shares/share-2b1b64b3-e94c-b1b8-8385-49cff45eee24"
  persistentVolumeReclaimPolicy: "Recycle"